# service: vxi-absent-tracker
# runtime: python312

entrypoint: gunicorn -b :$PORT JAM_AGENT_NOTIFICATION_TRACKER.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: JAM_AGENT_NOTIFICATION_TRACKER.settings

# handlers:
# - url: /static
#   static_dir: JAM_AGENT_NOTIFICATION_TRACKER/staticfiles/
# - url: /.*
#   script: auto
#############

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - vxi-absent-tracker
      - '--image'
      - >-
        us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA
      - '--region'
      - us-central1
images:
  - >-
    us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/${_IMAGE_NAME}:$SHORT_SHA
options:
  logging: CLOUD_LOGGING_ONLY