# Generated by Django 5.0.6 on 2024-07-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontroller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userabsentrequestdata',
            name='number',
            field=models.CharField(),
        ),
    ]
