# Generated by Django 5.0.6 on 2024-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycontroller', '0002_alter_userabsentrequestdata_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userabsentrequestdata',
            name='end_shift',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='userabsentrequestdata',
            name='start_shift',
            field=models.CharField(),
        ),
    ]
